"""Independent UDS/CDD CLI checks; Python packages are test-only.

Traffic is generated by udsoncan 1.26.1 and can-isotp 2.0.7. Original
CDD inputs are read-only; all results and generated logs go under artifacts.
"""
import argparse
import hashlib
import importlib.metadata
import json
from pathlib import Path
import subprocess
import xml.etree.ElementTree as ET

import cantools
from udsoncan import Response, MemoryLocation, AsciiCodec
from udsoncan import services as svc
from verify_isotp import generate, oracle
import can


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--exe', type=Path, default=Path('dist/canlog.exe'))
    ap.add_argument('--artifacts', type=Path, required=True)
    ap.add_argument('--cdd-samples', type=Path, required=True)
    ap.add_argument('--vector-cdd', type=Path)
    args = ap.parse_args()
    versions = {p: importlib.metadata.version(p) for p in
                ('udsoncan', 'can-isotp', 'python-can', 'cantools')}
    assert versions == {'udsoncan': '1.26.1', 'can-isotp': '2.0.7',
                        'python-can': '4.6.1', 'cantools': '43.0.2'}, versions
    args.artifacts.mkdir(parents=True, exist_ok=False)
    exe = args.exe.resolve()
    evidence = {'binary': str(exe), 'binary_sha256': sha(exe), 'versions': versions,
                'commands': [], 'cases': [], 'originals': {}}
    route = {'name': 'ecu', 'channel': 1, 'kind': 'physical', 'profile': 'classic',
             'addressing': 'normal', 'request': {'id': 0x7e0, 'extended': False},
             'response': {'id': 0x7e8, 'extended': False}, 'timeout_ns': 1_000_000_000}
    routes = args.artifacts / 'routes.json'
    routes.write_text(json.dumps({'schema_version': 1, 'routes': [route]}))
    base = {'schema_version': 1, 'routes': [{'route': 'ecu', 'protocol': 'uds2013',
            'p2_ns': 50_000_000, 'p2_star_ns': 100_000_000,
            'transaction_max_duration_ns': 500_000_000}]}
    policy = args.artifacts / 'policy.json'
    policy.write_text(json.dumps(base))

    def run(command, expected=0):
        command = list(map(str, command))
        proc = subprocess.run([str(exe), *command], capture_output=True)
        item = {'argv': command, 'exit': proc.returncode,
                'stderr': proc.stderr.decode('utf-8', errors='replace')}
        evidence['commands'].append(item)
        assert proc.returncode == expected, item
        return proc

    def capture(name, packets):
        """packets: (direction, start_ns, bytes, optional_CF_step_ns)."""
        messages, known = [], {}
        for direction, start, data, *step in packets:
            wire_route = route if direction == 'request' else {
                **route, 'request': route['response'], 'response': route['request']}
            for i, frame in enumerate(generate(wire_route, data, None)):
                timestamp = start + i * (step[0] if step else 1_000_000)
                messages.append((timestamp, direction, frame))
            known.setdefault(('ecu', direction), []).append(data.hex().upper())
        messages.sort(key=lambda m: m[0])  # stable ties preserve record order
        source = args.artifacts / (name + '.asc')
        lines = ['base hex timestamps absolute', 'no internal events logged']
        external = []
        for t, direction, frame in messages:
            data = bytes(frame.data)
            lines.append(f'{t // 1_000_000_000}.{t % 1_000_000_000:09} 1 '
                         f'{frame.arbitration_id:X} {"Tx" if direction == "request" else "Rx"} '
                         f'd {len(data)} ' + ' '.join(f'{b:02X}' for b in data))
            external.append(can.Message(timestamp=t/1e9, channel=1,
                                        arbitration_id=frame.arbitration_id,
                                        is_extended_id=False, data=data))
        source.write_text('\n'.join(lines) + '\n')
        assert oracle(external, [route]) == known
        return source

    def analyze(name, packets, expected, assigned=policy, status=0):
        source = capture(name, packets)
        output = args.artifacts / (name + '.jsonl')
        report = args.artifacts / (name + '.report.json')
        run(['uds', source, '--routes', routes, '--policy', assigned,
             '-o', output, '--report', report], status)
        rows = [json.loads(s) for s in output.read_text().splitlines()]
        actual = [r for r in rows if r['kind'].startswith('uds_')]
        assert [r['status'] for r in actual] == expected, actual
        assert len({r['result_key'] for r in rows}) == len(rows)
        metadata = json.loads(report.read_text())
        assert metadata['published'] and metadata['scan_complete']
        assert metadata['status'] == ('complete' if status == 0 else 'partial')
        evidence['cases'].append({'name': name, 'input_sha256': sha(source),
                                  'statuses': expected, 'verified': True})
        return actual, metadata

    try:
        # Requests come from an independent UDS library, including transfer BSC 0x81.
        cases = [
            (svc.DiagnosticSessionControl.make_request(3), '5003003201F4'),
            (svc.ECUReset.make_request(1), '5101'),
            (svc.ClearDiagnosticInformation.make_request(), '54'),
            (svc.ReadDTCInformation.make_request(1, status_mask=255), '5901FF010004'),
            (svc.ReadDTCInformation.make_request(2, status_mask=255), '5902FF01020378'),
            (svc.ReadDataByIdentifier.make_request([0xf190], {0xf190: AsciiCodec(17)}),
             '62F190' + b'WVWZZZ1JZXW000001'.hex()),
            (svc.SecurityAccess.make_request(1, svc.SecurityAccess.Mode.RequestSeed), '6701AABB'),
            (svc.WriteDataByIdentifier.make_request(0xf191, 'A', {0xf191: AsciiCodec(1)}), '6EF191'),
            (svc.RoutineControl.make_request(0xff00, 1), '7101FF0001'),
            (svc.RequestDownload.make_request(MemoryLocation(0x1000, 0x4000, 16, 16)), '742000FF'),
            (svc.TransferData.make_request(0x81, b'A'), '7681'),
            (svc.RequestTransferExit.make_request(), '77'),
            (svc.TesterPresent.make_request(), '7E00'),
        ]
        for i, (req, text) in enumerate(cases):
            data = req.get_payload()
            resp = bytes.fromhex(text)
            external = Response.from_payload(resp)
            assert external.valid and external.positive
            assert external.service.response_id() == data[0] + 0x40
            result, _ = analyze('service_' + f'{data[0]:02X}_{i}',
                                [('request', 0, data), ('response', 10_000_000, resp)], ['positive'])
            assert result[0]['request']['data_hex'] == data.hex().upper()
            assert result[0]['response']['data_hex'] == resp.hex().upper()
            assert result[0]['request_last_to_response_first_ns'] == 10_000_000
            assert result[0]['data_semantics'] == 'opaque_no_cdd'
        req = cases[5][0].get_payload()
        vin = bytes.fromhex(cases[5][1])
        negative = Response.from_payload(bytes.fromhex('7F2231'))
        pending = Response.from_payload(bytes.fromhex('7F2278'))
        assert negative.valid and negative.code == 0x31 and pending.code == 0x78
        analyze('negative', [('request', 0, req), ('response', 20_000_000, bytes.fromhex('7F2231'))], ['negative'])
        result, _ = analyze('pending_positive', [('request', 0, req),
                            ('response', 20_000_000, bytes.fromhex('7F2278')),
                            ('response', 90_000_000, vin)], ['pending', 'positive'])
        assert result[-1]['pending_count'] == 1
        result, _ = analyze('timely_ff_late_cf', [('request', 0, req),
                            ('response', 40_000_000, vin, 25_000_000)], ['positive'])
        assert result[0]['request_last_to_response_first_ns'] == 40_000_000
        assert result[0]['request_first_to_response_last_ns'] == 90_000_000
        analyze('ambiguous', [('request', 0, req), ('request', 1_000_000, req),
                             ('response', 10_000_000, vin)], ['ambiguous', 'ambiguous'], status=3)
        analyze('late_response', [('request', 0, req), ('response', 60_000_000, vin)],
                ['no_response_observed', 'orphan'], status=3)
        analyze('eof', [('request', 0, req)], ['incomplete'], status=3)

        files = sorted(args.cdd_samples.rglob('*.cdd'))
        assert len(files) == 4, files
        if args.vector_cdd:
            files.append(args.vector_cdd)
        inspected = {}
        for original in files:
            original = original.resolve()
            evidence['originals'][str(original)] = sha(original)
            expected = 3 if original.name == 'invalid-bo-example.cdd' else 0
            result = run(['cdd-info', original, '--allow-experimental'], expected)
            info = json.loads(result.stdout)
            (args.artifacts / (original.stem + '.cdd-info.json')).write_text(json.dumps(info, indent=2))
            assert info['sha256'] == sha(original)
            assert info['profile_maturity'] == 'experimental'
            root = ET.parse(original).getroot()
            qualifiers = [e.findtext('QUAL') for e in root.iter('ECU')]
            assert [e['qualifier'] for e in info['ecus']] == qualifiers
            try:
                independent = cantools.database.load_file(original, database_format='cdd')
                assert expected == 0
                external_dids = [{'identifier': d.identifier, 'name': d.name} for d in independent.dids]
                independent_error = None
            except cantools.database.UnsupportedDatabaseFormatError as error:
                assert expected == 3 and '4321' in str(error)
                assert any(i['code'] == 'CDD-BIT-004' for i in info['load_issue_examples'])
                external_dids, independent_error = [], str(error)
            evidence['cases'].append({'name': original.name, 'protocol': info['protocol'],
                                      'engine_dids': info['did_count'], 'cantools_items': external_dids,
                                      'independent_error': independent_error, 'verified': True})
            inspected[original.name] = (original, info)

        for filename, ecu, variant in [('example-diddatarefs.cdd', 'SBS_Test', 'Base_Variant'),
                                      ('UDS-ExampleEcu-5.1.0.cdd', 'Door', 'CommonDiagnostics')]:
            if filename not in inspected:
                continue
            original, info = inspected[filename]
            assert info['protocol'] == 'Uds'
            assigned = json.loads(json.dumps(base))
            assigned['routes'][0]['cdd'] = {'path': str(original), 'ecu': ecu, 'variant': variant,
                                           'allow_experimental': True}
            binding = args.artifacts / (original.stem + '.policy.json')
            binding.write_text(json.dumps(assigned))
            session_response = bytes.fromhex('5001003201F4')
            session = svc.DiagnosticSessionControl.make_request(1).get_payload()
            decoded, metadata = analyze(original.stem + '_session',
                                 [('request', 0, session), ('response', 10_000_000, session_response)],
                                 ['positive'], assigned=binding)
            cdd = decoded[0]['cdd']
            assert cdd['status'] == 'decoded', cdd
            assert cdd['document_sha256'] == sha(original)
            assert cdd['request_context'] and cdd['response']['schema_version'] == 2
            fields = cdd['response']['fields']
            by_name = {f['key'].split('/')[-1]: f for f in fields}
            independent = cantools.database.load_file(original, database_format='cdd')
            # cantools' identifier dictionary merges subfunctions from different
            # services. Select the explicit session definition from the full list.
            session_did = next(d for d in independent.dids
                               if d.identifier == 1 and d.name == 'DefaultSession')
            values = session_did.decode(session_response[2:])
            assert values['P2'] == 50 and values['P2Ex'] == 5000
            assert by_name['P2']['raw']['value'] == '50'
            assert by_name['P2Ex']['raw']['value'] == '500'
            assert float(by_name['P2Ex']['physical']['value']) == values['P2Ex']
            assert metadata['cdd_counts'] == {'decoded': 1}
            evidence['cases'].append({'name': original.stem + '_session_fields',
                                      'reference': values, 'verified': True})
            if filename.startswith('UDS-'):
                decoded, _ = analyze('cdd_vin_pending_negative', [('request', 0, req),
                         ('response', 20_000_000, bytes.fromhex('7F2278')),
                         ('response', 90_000_000, vin), ('request', 200_000_000, req),
                         ('response', 210_000_000, bytes.fromhex('7F2231'))],
                         ['pending', 'positive', 'negative'], assigned=binding, status=3)
                assert [r['cdd']['status'] for r in decoded] == [
                    'decoded_with_diagnostics', 'decoded', 'decoded_with_diagnostics']
                for r in (decoded[0], decoded[2]):
                    assert r['cdd']['response']['diagnostics'][0]['code'] == 'CDD-NRC-001'
                fields = decoded[1]['cdd']['response']['fields']
                value = next(f['raw']['value'] for f in fields if f['key'].endswith('/VIN'))
                response = svc.ReadDataByIdentifier.interpret_response(
                    Response.from_payload(vin), [0xf190], {0xf190: AsciiCodec(17)})
                assert bytes.fromhex(value).decode() == response.service_data.values[0xf190]
                evidence['cases'].append({'name': 'cdd_vin_field_and_nrc_diagnostics',
                    'vin': response.service_data.values[0xf190], 'verified': True})

        # Unknown protocol stays inspectable but cannot be assigned to a UDS route.
        original, _ = inspected['example.cdd']
        bad = json.loads(json.dumps(base))
        bad['routes'][0]['cdd'] = {'path': str(original), 'ecu': 'Any_ECU_example',
                                  'variant': 'COMMON_DIAGNOSTICS', 'allow_experimental': True}
        bad_path = args.artifacts / 'unknown.policy.json'
        bad_path.write_text(json.dumps(bad))
        source = capture('unknown_protocol', [('request', 0, req)])
        dest = args.artifacts / 'must-not-publish.jsonl'
        proc = run(['uds', source, '--routes', routes, '--policy', bad_path, '-o', dest], 1)
        assert b'protocol Unknown' in proc.stderr and not dest.exists()
        for original, identity in evidence['originals'].items():
            assert sha(Path(original)) == identity, original
        assert sha(exe) == evidence['binary_sha256']
        evidence['passed'] = True
    finally:
        (args.artifacts / 'results.json').write_text(json.dumps(evidence, indent=2))


if __name__ == '__main__':
    main()
